/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javax.swing.UIDefaults.LazyInputMap;

import main.java.org.example.GreedySingleton;
import main.java.org.example.LazySingleton;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        System.out.println("Starting app");

        GreedySingleton instance = GreedySingleton.getInstance();
        System.out.println(instance.getPassword());
        System.out.println(instance);

        GreedySingleton.resetInstance();
        System.out.println(GreedySingleton.getInstance());
     
        System.out.println("Parrt 2");

        LazySingleton lazy_instance = LazySingleton.getInstance();
        System.out.println(lazy_instance.getPassword());
        System.out.println(lazy_instance);

        LazySingleton.resetInstance();
        System.out.println(LazySingleton.getInstance());
    }
}
