/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Szin rozsa = new Rozsaszin();
        Alakzat gomb = new Gomb(rozsa, 2);
        System.out.println("A gömböt befesteni: " + gomb.getAr() + " Ft");


        Robot robi = new Robot(200, 1);
        Robot2Ember emberRobi = new Robot2Ember(robi);

        System.out.println(emberRobi.getIQ());
        System.out.println(emberRobi.getIgSzam());


        ArrayList<MovingParticle> particles = new ArrayList<>();
        Particle flyweight = new Particle(
            "piros", "/home/game/particle.png");

        for (int i = 0; i < 100_000_0; i++){
            particles.add(
                new MovingParticle(flyweight, i, i)
            );
        }

        Runtime runtime = Runtime.getRuntime();
    
        long usedMemory = runtime.totalMemory() 
                            - runtime.freeMemory();
        long usedMemoryMB = usedMemory / (1024 * 1024);

        System.out.println("Used Memory: "
                 + usedMemoryMB + " MB");
    }
}
