/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Karacsonyfa f1 = new GirlandDisz(new GirlandDisz(new CsillagDisz(new LucFenyo())));
        Karacsonyfa f2 = new BicikliDisz(new Gergely());

        System.out.println(f1.GetAr());
        System.out.println(f1.Kirajzolas());

        System.out.println(f2.GetAr());
        System.out.println(f2.Kirajzolas());
    }
}
