/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
    static final int SZEL = 20;
    static final int MAGAS = 10;

    public static void main(String[] args) {
        Kacsa kacsa = new Kacsa(
            new SimaHapogas(),
            new JolRepul(),
            new Fecser()
        );

        kacsa.hapog();
        kacsa.repul();
        kacsa.eszik();

        System.out.println("Stratégia csere");

        kacsa.setHapogasStrategia(new NemaHapogas());

        kacsa.hapog();

        Jatekos jatekos = new Jatekos(null);
        int SZEL = 20;
        int MAGAS = 10;

        jatekos.x = SZEL / 2;
        jatekos.y = MAGAS / 2;

        jatekos.allapotValtas(new SetalasAllapot(jatekos));
        boolean fut = true;
        Scanner scanner = new Scanner(System.in);

        while (fut) {
            rajzol(jatekos);

            System.out.println("w=ugrás a=blara d=jobbra s=esés q=kilép");
            String input = scanner.nextLine();

            switch (input) {
                case "w":
                    jatekos.ugras();
                    break;
                case "a":
                    jatekos.balraMozog();
                    break;
                case "s":
                    jatekos.esni();
                    break;
                case "d":
                    jatekos.jobbraMozog();
                    break;
                case "q":
                    fut = false;
                    break;
            }

            hatarEllenorzes(jatekos);
            torolKepernyo();
        }

        scanner.close();
    }

    static void rajzol(Jatekos jatekos) {
        for (int y = 0; y < 10; y++){
            for (int x = 0; x < 20; x++) {
                if( x == jatekos.x && y == jatekos.y){
                    System.out.print("P");
                }
                else {
                    System.out.print(".");
                }
            }
            System.out.println();
        }
    }

    static void hatarEllenorzes(Jatekos jatekos) {
        if (jatekos.x < 0) jatekos.x = 0;
        if (jatekos.x >= SZEL) jatekos.x = SZEL - 1;

        if (jatekos.y < 0) jatekos.y = 0;
        if (jatekos.y >= MAGAS) jatekos.y = MAGAS - 1;
    }

    static void torolKepernyo() {
        System.out.println("\n\n\n\n\n\n\n\n\n\n");
    }
}
