/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public int Addition(int a, int b){
        return a + b;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        ForroItal f1 = new TeaFozes();
        System.out.println(f1.CreateForroItal());

        ForroItal f2 = new RumosTeaFozes();
        System.out.println(f2.CreateForroItal());

        ForroItal f3 = new KaveFozes();
        System.out.println(f3.CreateForroItal());

        ForroItal f4 = new KaramellasCsokisIrKave();
        System.out.println(f4.CreateForroItal());
    }
}
